# Generated by Django 4.2.5 on 2023-09-30 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escapegame.game')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=5000)),
                ('answer', models.CharField(max_length=128)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escapegame.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameBranchEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('game_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escapegame.gamebranch')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escapegame.step')),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=1000)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escapegame.step')),
            ],
        ),
    ]
