# Generated by Django 4.2.5 on 2023-09-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapegame', '0003_alter_step_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamebranch',
            name='name',
            field=models.CharField(default='main', max_length=255),
            preserve_default=False,
        ),
    ]
