# Generated by Django 4.2.5 on 2023-09-30 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escapegame', '0004_gamebranch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escapegame.scenarionode')),
            ],
        ),
        migrations.RenameModel(
            old_name='GameBranch',
            new_name='Scenario',
        ),
        migrations.DeleteModel(
            name='GameBranchEntry',
        ),
        migrations.AddField(
            model_name='scenarionode',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escapegame.scenario'),
        ),
        migrations.AddField(
            model_name='scenarionode',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escapegame.step'),
        ),
    ]
