# Generated by Django 4.2.5 on 2023-09-30 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escapegame', '0006_alter_scenarionode_parent_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarionode',
            name='parent_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escapegame.scenarionode'),
        ),
    ]
