# Generated by Django 4.2.5 on 2023-10-01 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escapegame', '0007_alter_scenarionode_parent_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='escapegame.game'),
        ),
    ]
