# Generated by Django 4.2.5 on 2023-10-01 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escapegame', '0008_alter_scenario_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='escapegame.step'),
        ),
        migrations.AlterField(
            model_name='step',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='escapegame.game'),
        ),
    ]
