# Generated by Django 4.2.5 on 2023-10-01 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escapegame', '0009_alter_clue_step_alter_step_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarionode',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_nodes', to='escapegame.scenario'),
        ),
        migrations.AlterField(
            model_name='scenarionode',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='escapegame.step'),
        ),
    ]
