# Generated by Django 4.2.5 on 2023-11-08 19:47

from django.db import migrations, models

from slugify import slugify

def generate_slug(apps, schema_editor):
    # we get main model
    Scenario = apps.get_model('escapegame', 'scenario')
    for scenario in Scenario.objects.all():
        scenario.slug = slugify(scenario.name)
        scenario.save()

class Migration(migrations.Migration):

    dependencies = [
        ('escapegame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='slug',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.RunPython(generate_slug),
    ]
