# Generated by Django 4.2.5 on 2023-11-10 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escapegame', '0002_image'),
        ('escapegame', '0002_scenario_slug'),
    ]

    operations = [
    ]
