# Generated by Django 4.2.5 on 2023-11-16 15:10

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import escapegame.models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('escapegame', '0004_image_game_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='escapegame.game'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='slug',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
