# Generated by Django 4.2.5 on 2026-07-15 18:14

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import escapegame.models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('escapegame', '0005_alter_image_game_alter_image_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escapegame.theme'),
        ),
    ]
