# Generated by Django 4.2.5 on 2026-09-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapegame', '0006_theme_alter_image_image_game_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='is_last',
            field=models.BooleanField(default=False),
        )
    ]
