# Generated by Django 4.2.5 on 2026-09-30 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escapegame', '0007_step_is_last_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndGameText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=5000)),
                ('min_time', models.IntegerField()),
                ('max_time', models.IntegerField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_game_texts', to='escapegame.step')),
            ],
        ),
    ]
